FROM node:19-alpine

RUN apk update && apk upgrade && apk add bash
RUN mkdir app

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

RUN yarn build

RUN npx prisma generate

CMD [ "yarn", "start:prod" ]

EXPOSE 3000
