name: CI-pr

on: pull_request_target

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
      - run: yarn install
      - run: yarn build
      - run: yarn lint

  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
      - run: yarn install
      - run: yarn build
      - run: yarn test

  E2E-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
      - run: yarn install
      - run: yarn build
      - run: yarn test:e2e

  Coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '19.x'
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: yarn jest -o --ci --json --coverage --testLocationInResults --outputFile=report.json
