name: CI
on: push
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
      - run: yarn install
      - run: yarn build
      - run: yarn test
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
      - run: yarn install
      - run: yarn build
      - run: yarn lint
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
  Coverage:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
      - run: yarn install
      - run: yarn build
      - run: yarn test:cov
